### PR TITLE
Fix call to Record resource with last kinto release. — Fixes #97

### LINKED ISSUE #97: __init__() takes 2 positional arguments but 3 were given
Setting up kinto-attachment 0.7.0 locally against Kinto 3.2.1, Ubuntu 16.05, Python 3.5.1 (standard dist package).

`kinto.ini`:

```ini
[app:main]
use = egg:kinto

# Required by integration tests
kinto.flush_endpoint_enabled = true

# Required by basic auth
kinto.userid_hmac_secret = a-secret-string

# Allow browsing all buckets
kinto.bucket_read_principals = system.Authenticated

# Plugins registration
kinto.includes = kinto.plugins.default_bucket
                 kinto_attachment

# Kinto-attachment
kinto.attachment.base_url = http://cdn.service.org/files/
kinto.attachment.folder = {bucket_id}/{collection_id}
kinto.attachment.keep_old_files = true
kinto.attachment.base_path = /tmp

[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 8888
```

The server starts fine:

```
$ .venv/bin/kinto --ini test/kinto.ini start
Starting server in PID 7954.
serving on http://0.0.0.0:8888
```

But requesting `GET http://0.0.0.0:8888/v1/buckets/custom/collections/plop/records/96a38b32-2bf2-47a2-9ddc-944965ebd6dd/attachment` explodes with:

```
ERROR:kinto.core.views.errors:"GET   /v1/buckets/custom/collections/plop/records/96a38b32-2bf2-47a2-9ddc-944965ebd6dd/attachment" ? (? ms) __init__() takes 2 positional arguments but 3 were given agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 authn_type=None errno=None exception=Traceback (most recent call last):
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/pyramid_tm/compat.py", line 15, in reraise
    raise value
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/pyramid/router.py", line 127, in handle_request
    root = root_factory(request)
  File "/home/niko/work/kinto-http.js/.venv/lib/python3.5/site-packages/kinto_attachment/utils.py", line 32, in __init__
    resource = Record(request, self)
TypeError: __init__() takes 2 positional arguments but 3 were given lang=fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4 uid=None
```

What am I doing wrong? Edit: I know this GET request is not supported, though I was not expecting it to raise.

### PR DESCRIPTION
**Pull request by Natim**
r? leplatrem
f? @n1k0

### CODE REVIEW

**Comment by Natim** [comment]
The tests were all failing so I didn't had to add new ones.

**Comment by n1k0** [comment]
> The tests were all failing so I didn't had to add new ones.

You mean master was broken and nobody noticed?

**Comment by Natim** [comment]
> You mean master was broken and nobody noticed?

Yes it doesn't triggers the kinto-attachment tests when kinto is updated.
We would have noticed the next time we would have work on kinto-attachment...

**Comment by Natim** [comment]
@n1k0 what you said is the reason why we need this: https://github.com/mozilla-services/kinto-dist/issues/27

**Comment by n1k0** [comment]
Naively I'd expect this very repo to have integration tests run against the supported kinto server versions...

**Comment by Natim** [comment]
This very repos have got some but if you don't run them you will never know.

**Comment by n1k0** [comment]
I'm confused :) If we have integration tests in this repo, why don't we run them on Travis to detect when master actually breaks against a given kinto server version? That's what we do with kinto.js, it's convenient.

**Comment by Natim** [comment]
That's just because kinto broke the plugin but we didn't run any tests in kinto-attachment since because nothing changed in this plugin.

**Pull request merged**
