### PR TITLE
File bundle support

### PR DESCRIPTION
**Pull request by almet**
This adds a way to upload a set of files (a bundle) into a record. It's the first step towards having Kinto able to embed WebApps.

There is quite some refactor going on here, so let me know what you think about it.

This is not done yet:

- [ ] Add support for multiple folders settings (the folders could be different for bundles and for single attachment)
- [x] Do not keep the old files for multiple files
- [x] Rename the feature to "files bundle" rather than "attachments" ?
- [ ] Make the last failing test pass

@leplatrem a quick review before you go to holidays? :-)

### CODE REVIEW

**Comment by leplatrem** [comment]
Oh! I'm surprised! Unless I have a blackout, I don't remember we exchanged about this idea! I recall we said we didn't want to handle multiple files per record during our first design phases!

That doesn't mean I'm against it a priori, but I have some questions :)

I'm a bit concerned about one thing: there is now two ways to achieve the same thing. We'll have to document two ways, explain the difference between both approach, and spread some *ifs* here and there in the documentation. In the clients, we'll also have to have some *ifs* to distinguish multiple from single file attachments, which does not sound (at first sight) like a very good idea.

For the «application bundles», why not use a dedicated collection with one file per record?
`/buckets/myapp/collections/assets/records`:
```js
{"data": [
  {"filename": "index.html", "attachment": {...}},
  {"filename": "script.js", "attachment": {...}},
]}
```

Please give me some context, and what lead you to this solution :) 

Otherwise, **huge thanks** for the refactoring, it was beginning to become very necessary :)

**Comment by leplatrem** [comment]
Some more clarifications about my point of view (*since I'll be on holiday*):

* I'm a fan of the «web app bundles» idea!
* Before adding new features (and possibly bloat the docs), I wish we had a clear statement about the blockers to achieve it with the current features
* If the `randomize` feature is the limitation, we could probably focus on that (*I can see it is true in one endpoint and false in the other*)
* I don't see the advantage of an endpoint where all the files are posted/updated/deleted together. Would you reupload all your png/css/odf everytime a `.js` file changes?
* We could probably split the refactor from this PR :)

I hope I don't sound harsh nor narrow-minded, I just want to question the approach of adding a new feature instead of reusing what's available :)

**Comment by almet** [comment]
No worries! I'm taking some time to answer since otherwise I think this will take a week of wait. 

First thanks for the feedback! To add some context here I have to explain why I'm doing it this way. 

For embedded applications I need to post multiple files. Rather than creating a collection per app I wanted to have a collection which contains all the applications. having the apps rooted in a bucket makes it easy to port. I don't want to have an app bucket if possible and keeping the application next to the data seems a good idea (it's easier to handle data versioning for instance ). 

This pull request serves as a discussion. I'm fine with not merging all of it if we decide to go another way. 

I also agree that having two ways to do the same thing is probably a bad idea. I was envisioning to deprecate the single file endpoint but it would then need to have ways to be configurable :

- should the ID be randomized or not? 
- we probably should provide a way to patch the record with some files so everything is not deleted each time. 

What do you think?

**Comment by almet** [comment]
Following a discussion with @leplatrem I'm closing this pull request and opening another one for the refactoring.

**Pull request closed without merging**
