### PR TITLE
Add demo to post files from browser

### PR DESCRIPTION
**Pull request by leplatrem**
* [x] Fix CORS errors on server
* [x] List existing records when combo «category» is changed ?

### CODE REVIEW

**Comment by almet** [comment]
Redirecting just after a POST seems odd to me. Rather, you could directly return a 201 or 202 (depending if the record is created within the request), with the location of the newly created record in the "Location" header, as specified by the HTTP spec.

**Comment by Natim** [comment]
Redirecting after a POST is usually considered as a best practice to make sure a refresh will not post the file twice.

**Comment by almet** [comment]
A refresh from where?

**Comment by Natim** [comment]
> A refresh from where?

From the form using the browser.

**Comment by almet** [comment]
According to the W3.org spec, when the METHOD is not HEAD or GET, user agents should prompt the user before re-executing the request at the new location.

**Comment by Natim** [comment]
Yes, it is true, they do but it doesn't prevent the user for pressing yet on such a message.

**Comment by almet** [comment]
When you say it's a best practice, do you have some docs / specs to point to? (I'm trying to find, but not much so far).

From what I know, a redirect on a webpage usually happens to avoid displaying the page with the form again to the user, and in our case it's orthogonal to the API we're exposing, it seems.

**Comment by leplatrem** [comment]
This demo works as expected: http://webm.land/w/XvSW/

I request a merge :)

**Comment by Natim** [comment]
Great :+1:

**Pull request merged**
